apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/atlas-operator
  - ../base/aws-load-balancer-controller
  - ../base/cilium
  - ../base/cloudnative-pg
  - ../base/external-dns
  - ../base/gapi
  # Karpenter is deployed via separate Flux Kustomization (see clusters/mycluster-0/infrastructure.yaml)
