apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  timeout: 8m0s
  sourceRef:
    kind: ExternalArtifact
    name: security-artifact
  path: ./security/mycluster-0
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
      - kind: Secret
        name: cert-manager-openbao-approle
  dependsOn:
    - name: eks-pod-identities
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: security
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kyverno
      namespace: security
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: security
