apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/headlamp
  - ../base/harbor
  - ../base/homepage
  - ../base/pev2
  # Enabling only when needed for cost reasons
  # - ../base/dagger-engine
  # - ../base/gha-runners
