apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tooling

resources:
  - app.yaml

commonLabels:
  app.kubernetes.io/name: pev2
  app.kubernetes.io/component: visualizer
  app.kubernetes.io/managed-by: crossplane
