---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./flux-config/mycluster-0
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      domain_name: "cloud.ogenki.io"
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
      - kind: Secret
        name: eks-mycluster-0-vars
        optional: true
  dependsOn:
    - name: crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
