apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure

resources:
  - allow-gateway-l7-proxy.yaml
  - platform-private-gateway-certificate.yaml
  - tailscale-gatewayclass-config.yaml
  - tailscale-gatewayclass.yaml
  - platform-tailscale-general-gateway.yaml
  - platform-tailscale-admin-gateway.yaml
