apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - gateway-unsecure.yaml
  - helmrelease-echo-1.yaml
  - helmrelease-echo-2.yaml
  - httproute.yaml
  - httproute-split.yaml
  - httproute-unsecure.yaml
  - source.yaml
