apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure

resources:
  - grafana-dashboard.yaml
  - grafana-dashboard-query-performance.yaml
  - grafana-dashboard-query-plan-correlation.yaml
  - helmrelease.yaml
  - s3-bucket.yaml
