apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/external-secrets

patches:
  - path: helmrelease.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: external-secrets
      namespace: kube-system
      version: v2beta1
