apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-configuration
  namespace: flux-system
spec:
  prune: true
  interval: 1m0s
  timeout: 3m0s
  path: ./infrastructure/mycluster-0/crossplane/configuration
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
  dependsOn:
    - name: crossplane-providers
